export const DOCTOR = {
  name: "Dr. Priya Sharma",
  role: "doctor",
  image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2",
  specialization: "Cardiologist",
  experience: 12,
  doctorEmail: "priya.sharma@example.com",
  password: "SecurePassword123",
  availability: "available",
  qualification: "MBBS, MD (Cardiology)",
  rating: 4.8,
  successRate: 96,
  about:
    "Experienced cardiologist specializing in the diagnosis and treatment of heart diseases. Dedicated to providing personalized care and improving patient outcomes through evidence-based medicine.",
  scheduleSlots: [
    "12/01/2025 - 10:10 AM",
    "12/01/2025 - 11:30 AM",
    "13/01/2025 - 09:00 AM",
    "13/01/2025 - 02:15 PM",
    "14/01/2025 - 04:00 PM",
  ],
  fee: 1500,
  totalAppointments: 20,
  completed: 15,
  cancelled: 3,
  totalEarnings: 22500,
};

export const DUMMY_APPOINTMENTS = [
  {
    _id: "apt_001",
    patient: {
      _id: "pat_001",
      name: "John Doe",
      gender: "male",
      age: 32,
      phone: "9876543210",
    },
    doctor: {
      _id: "doc_001",
      name: "Dr. Priya Sharma",
      specialization: "Cardiologist",
    },
    status: "completed",
    timeSlot: "12/01/2025 - 10:10 AM",
    reason: "Chest Pain",
    adminCancel: false,
    paymentMethod: "online",
    cancelReason: "",
    fee: 1500,
  },
  {
    _id: "apt_002",
    patient: {
      _id: "pat_002",
      name: "Sarah Wilson",
      gender: "female",
      age: 28,
      phone: "9876543211",
    },
    doctor: {
      _id: "doc_001",
      name: "Dr. Priya Sharma",
      specialization: "Cardiologist",
    },
    status: "confirmed",
    timeSlot: "12/01/2025 - 11:30 AM",
    reason: "Heart Palpitations",
    adminCancel: false,
    paymentMethod: "cash",
    cancelReason: "",
    fee: 1500,
  },
  {
    _id: "apt_003",
    patient: {
      _id: "pat_003",
      name: "Michael Brown",
      gender: "male",
      age: 45,
      phone: "9876543212",
    },
    doctor: {
      _id: "doc_002",
      name: "Dr. Rahul Verma",
      specialization: "Neurologist",
    },
    status: "pending",
    timeSlot: "13/01/2025 - 09:00 AM",
    reason: "Migraine",
    adminCancel: false,
    paymentMethod: "online",
    cancelReason: "",
    fee: 1800,
  },
  {
    _id: "apt_004",
    patient: {
      _id: "pat_004",
      name: "Emily Davis",
      gender: "female",
      age: 36,
      phone: "9876543213",
    },
    doctor: {
      _id: "doc_003",
      name: "Dr. Anjali Nair",
      specialization: "Dermatologist",
    },
    status: "cancelled",
    timeSlot: "13/01/2025 - 02:15 PM",
    reason: "Skin Allergy",
    adminCancel: true,
    paymentMethod: "online",
    cancelReason: "Doctor unavailable",
    fee: 1200,
  },
  {
    _id: "apt_005",
    patient: {
      _id: "pat_005",
      name: "David Miller",
      gender: "male",
      age: 51,
      phone: "9876543214",
    },
    doctor: {
      _id: "doc_004",
      name: "Dr. Sneha Patel",
      specialization: "Orthopedic",
    },
    status: "completed",
    timeSlot: "14/01/2025 - 04:00 PM",
    reason: "Knee Pain",
    adminCancel: false,
    paymentMethod: "cash",
    cancelReason: "",
fee: 2000,
  },
  {
    _id: "apt_006",
    patient: {
      _id: "pat_006",
      name: "Sophia Taylor",
      gender: "female",
      age: 24,
      phone: "9876543215",
    },
    doctor: {
      _id: "doc_005",
      name: "Dr. Vikram Singh",
      specialization: "General Physician",
    },
    status: "confirmed",
    timeSlot: "15/01/2025 - 05:15 PM",
    reason: "Fever",
    adminCancel: false,
    paymentMethod: "online",
    cancelReason: "",
    fee: 800,
  },
];